# Generated by Django 6.0.5 on 2026-05-10 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labresult',
            old_name='date',
            new_name='date_tested',
        ),
        migrations.RenameField(
            model_name='labresult',
            old_name='result',
            new_name='result_value',
        ),
        migrations.AddField(
            model_name='labresult',
            name='status',
            field=models.CharField(default='Final', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portal.patient'),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('service', models.CharField(max_length=100)),
                ('status', models.CharField(default='Scheduled', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='portal.patient')),
            ],
        ),
    ]
